import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.philosophy': '核心理念',
    'nav.history': '发展历史',
    'nav.projects': '关键项目',
    'nav.technology': '核心技术',
    
    // Homepage
    'home.title': '敏捷芯片开发',
    'home.ai_expert': 'AI专家',
    'home.subtitle': '敏捷芯片开发专家助手',
    'home.description': '与敏捷芯片开发专家AI对话，获取关于SoC设计、RISC-V架构、敏捷方法论等专业知识和指导',
    'home.explore_more': '探索更多内容',
    'home.core_features': '敏捷芯片开发核心特性',
    'home.core_features_desc': '了解敏捷方法如何应用于芯片开发，带来前所未有的效率和创新',
    'home.achievements': '发展成果',
    'home.achievements_desc': '敏捷芯片开发在全球范围内取得的显著成就',
    'home.cta_title': '开始您的敏捷芯片开发之旅',
    'home.cta_desc': '深入了解敏捷方法论，探索成功案例，掌握核心技术，加入全球开源芯片开发社区',
    'home.learn_concepts': '学习核心理念',
    'home.development_history': '了解发展历程',
    
    // Features
    'feature.fast_iteration': '快速迭代',
    'feature.fast_iteration_desc': '通过短周期Sprint实现芯片设计的敏捷开发',
    'feature.collaborative_teams': '协作团队',
    'feature.collaborative_teams_desc': '打破传统孤岛，建立灵活协作的开发团队',
    'feature.advanced_tools': '先进工具',
    'feature.advanced_tools_desc': '采用Chisel、RISC-V等现代化开发工具和平台',
    'feature.success_cases': '成功案例',
    'feature.success_cases_desc': '香山处理器、Berkeley RISC-V等项目验证敏捷方法',
    'common.learn_more': '了解更多',
    
    // Achievements
    'achievement.manifesto': '敏捷硬件宣言发布',
    'achievement.projects': '开源芯片项目',
    'achievement.universities': '知名大学参与',
    'achievement.open_source': '开放源代码',
    
    // Chat
    'chat.expert_title': '敏捷芯片开发专家',
    'chat.expert_subtitle': 'AI助手 · 在线回答',
    'chat.placeholder': '询问敏捷芯片开发相关问题...',
    'chat.send_hint': 'Enter发送',
    'chat.welcome': '您好！我是敏捷芯片开发专家助手。我可以回答关于敏捷硬件开发方法论、SoC设计流程、开源芯片项目等相关问题。请问有什么可以帮助您的吗？',
    
    // Thinking process
    'thinking.analyzing': '🤔 正在分析您的问题，搜索相关的敏捷芯片开发知识...',
    'thinking.consulting': '🔍 正在查阅敏捷硬件宣言和SoC设计最佳实践...',
    'thinking.integrating': '⚡ 正在整合RISC-V、香山处理器等成功案例经验...',
    'thinking.generating': '💡 正在生成专业的技术解答和建议...',
    
    // Chat error messages
    'chat.no_understanding': '抱歉，我没有理解您的问题。请尝试询问关于敏捷芯片开发、SoC设计、或开源芯片项目的问题。',
    'chat.general_help': '很抱歉，我暂时无法回答这个问题。但我可以为您介绍敏捷芯片开发的基本概念、核心工具、成功案例等内容。请尝试询问更具体的问题。',

    // History Page
    'history.hero_tag': '发展历史',
    'history.hero_tag_en': 'History',
    'history.hero_title': '敏捷芯片开发',
    'history.hero_title_en': 'Agile Chip Development',
    'history.hero_subtitle': '发展历程',
    'history.hero_subtitle_en': 'Development History',
    'history.intro': '追溯敏捷方法论在芯片开发领域的演进历程，了解关键里程碑和发展趋势。',
    'history.intro_en': 'Tracing the evolution of agile methodologies in chip development, exploring key milestones and trends.',
    'history.hero_img_title': '从软件到硬件的敏捷之路',
    'history.hero_img_title_en': 'The Agile Journey: From Software to Hardware',
    'history.hero_img_desc': '见证芯片设计方法论的革命性变革',
    'history.hero_img_desc_en': 'Witness the revolutionary transformation of chip design methodologies',
    'history.timeline_title': '关键时间节点',
    'history.timeline_title_en': 'Key Milestones',
    'history.evolution_title': '发展阶段',
    'history.evolution_title_en': 'Evolution Phases',
    'history.evolution_feature': '主要特征：',
    'history.evolution_feature_en': 'Key Features:',
    'history.detail_timeline': '详细时间线',
    'history.detail_timeline_en': 'Detailed Timeline',
    'history.future_title': '未来展望',
    'history.future_title_en': 'Future Outlook',
    'history.future_desc': '随着开源EDA工具的成熟、AI技术的融入以及更多成功案例的涌现，敏捷芯片开发方法论将在未来十年内成为业界主流，推动整个半导体行业向着更加开放、高效、创新的方向发展。',
    'history.future_desc_en': 'With the maturity of open-source EDA tools, the integration of AI technologies, and the emergence of more success stories, agile chip development methodologies are set to become mainstream in the next decade, driving the semiconductor industry towards greater openness, efficiency, and innovation.',
    // Milestones
    'history.milestone.2001.title': '敏捷宣言诞生',
    'history.milestone.2001.title_en': 'Agile Manifesto',
    'history.milestone.2001.desc': '软件工程领域发布敏捷宣言，为后续硬件敏捷开发奠定理论基础',
    'history.milestone.2001.desc_en': 'The Agile Manifesto was published in software engineering, laying the theoretical foundation for agile hardware development.',
    'history.milestone.2001.impact': '理论基础',
    'history.milestone.2001.impact_en': 'Theoretical Foundation',
    'history.milestone.2010.title': 'Chisel语言发布',
    'history.milestone.2010.title_en': 'Chisel Released',
    'history.milestone.2010.desc': 'UC Berkeley发布Chisel硬件构造语言，提供敏捷硬件开发的关键工具',
    'history.milestone.2010.desc_en': 'UC Berkeley released the Chisel hardware construction language, providing a key tool for agile hardware development.',
    'history.milestone.2010.impact': '工具创新',
    'history.milestone.2010.impact_en': 'Tool Innovation',
    'history.milestone.2016.title': '敏捷硬件宣言',
    'history.milestone.2016.title_en': 'Agile Hardware Manifesto',
    'history.milestone.2016.desc': '加州大学伯克利分校正式提出敏捷硬件宣言，标志着敏捷理念系统性应用于硬件',
    'history.milestone.2016.desc_en': 'UC Berkeley formally proposed the Agile Hardware Manifesto, marking the systematic application of agile concepts to hardware.',
    'history.milestone.2016.impact': '方法论确立',
    'history.milestone.2016.impact_en': 'Methodology Established',
    'history.milestone.2019.title': 'RISC-V生态繁荣',
    'history.milestone.2019.title_en': 'RISC-V Ecosystem Flourishes',
    'history.milestone.2019.desc': 'RISC-V指令集架构成熟，为敏捷芯片开发提供开放平台',
    'history.milestone.2019.desc_en': 'The RISC-V ISA matured, providing an open platform for agile chip development.',
    'history.milestone.2019.impact': '生态建设',
    'history.milestone.2019.impact_en': 'Ecosystem Building',
    'history.milestone.2020.title': '全球化应用',
    'history.milestone.2020.title_en': 'Global Adoption',
    'history.milestone.2020.desc': '香山处理器等项目证明敏捷方法在大型芯片项目中的成功应用',
    'history.milestone.2020.desc_en': 'Projects like Xiangshan processor proved the successful application of agile methods in large-scale chip projects.',
    'history.milestone.2020.impact': '产业验证',
    'history.milestone.2020.impact_en': 'Industry Validation',
    // Evolution Phases
    'history.phase.0': '萌芽期',
    'history.phase.0_en': 'Emergence',
    'history.phase.0.period': '2001-2010',
    'history.phase.0.period_en': '2001-2010',
    'history.phase.0.desc': '软件敏捷方法论成熟，开始探索在硬件领域的应用可能性',
    'history.phase.0.desc_en': 'Agile methodologies in software matured, and exploration began for their application in hardware.',
    'history.phase.0.char.0': '理论探索',
    'history.phase.0.char.0_en': 'Theoretical Exploration',
    'history.phase.0.char.1': '工具缺乏',
    'history.phase.0.char.1_en': 'Lack of Tools',
    'history.phase.0.char.2': '概念验证',
    'history.phase.0.char.2_en': 'Proof of Concept',
    'history.phase.1': '发展期',
    'history.phase.1_en': 'Development',
    'history.phase.1.period': '2010-2016',
    'history.phase.1.period_en': '2010-2016',
    'history.phase.1.desc': '关键工具如Chisel出现，学术界开始系统性研究硬件敏捷开发',
    'history.phase.1.desc_en': 'Key tools like Chisel emerged, and academia began systematic research on agile hardware development.',
    'history.phase.1.char.0': '工具涌现',
    'history.phase.1.char.0_en': 'Emergence of Tools',
    'history.phase.1.char.1': '学术研究',
    'history.phase.1.char.1_en': 'Academic Research',
    'history.phase.1.char.2': '小规模实践',
    'history.phase.1.char.2_en': 'Small-scale Practice',
    'history.phase.2': '成熟期',
    'history.phase.2_en': 'Maturity',
    'history.phase.2.period': '2016-至今',
    'history.phase.2.period_en': '2016-Present',
    'history.phase.2.desc': '敏捷硬件宣言发布，大型开源项目验证方法论可行性',
    'history.phase.2.desc_en': 'The Agile Hardware Manifesto was published, and large open-source projects validated the methodology.',
    'history.phase.2.char.0': '方法论确立',
    'history.phase.2.char.0_en': 'Methodology Established',
    'history.phase.2.char.1': '生态完善',
    'history.phase.2.char.1_en': 'Ecosystem Improved',
    'history.phase.2.char.2': '产业应用',
    'history.phase.2.char.2_en': 'Industry Application',

    // Philosophy Page
    'philosophy.hero_tag': '核心理念与方法论',
    'philosophy.hero_tag_en': 'Philosophy & Methodology',
    'philosophy.hero_title': '敏捷芯片开发',
    'philosophy.hero_title_en': 'Agile Chip Development',
    'philosophy.hero_subtitle': '核心理念',
    'philosophy.hero_subtitle_en': 'Core Philosophy',
    'philosophy.intro': '敏捷芯片开发借鉴了软件工程的敏捷思想，旨在应对传统芯片开发模式的挑战。',
    'philosophy.intro_en': 'Agile chip development draws on agile ideas from software engineering to address the challenges of traditional chip development.',
    'philosophy.manifesto_title': '敏捷硬件宣言',
    'philosophy.manifesto_title_en': 'Agile Hardware Manifesto',
    'philosophy.principle.0.title': '可工作的原型优于全面的文档',
    'philosophy.principle.0.title_en': 'Working Prototypes over Comprehensive Documentation',
    'philosophy.principle.0.desc': '注重快速构建可验证的硬件原型，而非完美的设计文档',
    'philosophy.principle.0.desc_en': 'Focus on building verifiable hardware prototypes quickly, rather than perfect design documents.',
    'philosophy.principle.1.title': '协作灵活的团队优于僵化的孤岛',
    'philosophy.principle.1.title_en': 'Collaborative Teams over Rigid Silos',
    'philosophy.principle.1.desc': '打破传统部门壁垒，建立跨学科协作的敏捷团队',
    'philosophy.principle.1.desc_en': 'Break down traditional barriers and build agile, cross-disciplinary teams.',
    'philosophy.principle.2.title': '改进工具和生成器优于改进实例',
    'philosophy.principle.2.title_en': 'Improving Tools & Generators over Improving Instances',
    'philosophy.principle.2.desc': '投资于开发工具和自动化，提高整体开发效率',
    'philosophy.principle.2.desc_en': 'Invest in tool and automation development to improve overall efficiency.',
    'philosophy.principle.3.title': '响应变化优于遵循计划',
    'philosophy.principle.3.title_en': 'Responding to Change over Following a Plan',
    'philosophy.principle.3.desc': '保持灵活性，能够快速适应需求变化和技术发展',
    'philosophy.principle.3.desc_en': 'Stay flexible and adapt quickly to changing requirements and technologies.',
    'philosophy.methodologies_title': '关键方法论',
    'philosophy.methodologies_title_en': 'Key Methodologies',
    'philosophy.method.0.name': 'Scrum for Hardware',
    'philosophy.method.0.name_en': 'Scrum for Hardware',
    'philosophy.method.0.desc': '将Scrum框架应用于硬件开发',
    'philosophy.method.0.desc_en': 'Applying the Scrum framework to hardware development.',
    'philosophy.method.1.name': '测试驱动开发',
    'philosophy.method.1.name_en': 'Test-Driven Development',
    'philosophy.method.1.desc': 'TDD方法在硬件设计中的应用',
    'philosophy.method.1.desc_en': 'Applying TDD in hardware design.',
    'philosophy.method.2.name': '持续集成/验证',
    'philosophy.method.2.name_en': 'Continuous Integration/Verification',
    'philosophy.method.2.desc': 'CI/CV在芯片开发中的实践',
    'philosophy.method.2.desc_en': 'Practicing CI/CV in chip development.',
    'philosophy.method.3.name': '模型驱动开发',
    'philosophy.method.3.name_en': 'Model-Driven Development',
    'philosophy.method.3.desc': 'MDD提高设计抽象层次',
    'philosophy.method.3.desc_en': 'MDD improves the level of design abstraction.',
    'philosophy.benefits_title': '敏捷方法的优势',
    'philosophy.benefits_title_en': 'Benefits of Agile Methods',
    'philosophy.benefit.0.title': '提高效率',
    'philosophy.benefit.0.title_en': 'Increased Efficiency',
    'philosophy.benefit.0.desc': '通过短周期迭代和快速反馈，大幅缩短开发周期',
    'philosophy.benefit.0.desc_en': 'Short-cycle iterations and rapid feedback greatly shorten development cycles.',
    'philosophy.benefit.1.title': '降低风险',
    'philosophy.benefit.1.title_en': 'Reduced Risk',
    'philosophy.benefit.1.desc': '早期验证和持续测试，及时发现和解决问题',
    'philosophy.benefit.1.desc_en': 'Early validation and continuous testing help identify and solve problems promptly.',
    'philosophy.benefit.2.title': '增强创新',
    'philosophy.benefit.2.title_en': 'Enhanced Innovation',
    'philosophy.benefit.2.desc': '灵活响应变化，促进创新思维和技术探索',
    'philosophy.benefit.2.desc_en': 'Flexible response to change fosters innovation and technological exploration.',

    // Projects Page
    'projects.hero_tag': '关键项目与技术',
    'projects.hero_tag_en': 'Key Projects & Technologies',
    'projects.hero_title': '成功',
    'projects.hero_title_en': 'Success',
    'projects.hero_subtitle': '案例展示',
    'projects.hero_subtitle_en': 'Case Studies',
    'projects.intro': '探索全球范围内敏捷芯片开发的成功项目，了解先进技术和工具的实际应用。',
    'projects.intro_en': 'Explore successful agile chip development projects worldwide and learn about the practical application of advanced technologies and tools.',
    'projects.hero_img_title': '开源驱动创新',
    'projects.hero_img_title_en': 'Open Source Drives Innovation',
    'projects.hero_img_desc': 'RISC-V生态推动敏捷芯片开发蓬勃发展',
    'projects.hero_img_desc_en': 'The RISC-V ecosystem drives the flourishing of agile chip development.',
    'projects.case_studies_title': '成功案例',
    'projects.case_studies_title_en': 'Case Studies',
    'projects.visit_project': '访问项目',
    'projects.visit_project_en': 'Visit Project',
    'projects.key_tech_title': '核心技术栈',
    'projects.key_tech_title_en': 'Core Technology Stack',
    'projects.key_tech_desc': '敏捷芯片开发依托于现代化的工具链和技术栈，这些技术为快速迭代、自动化验证和协作开发提供了强有力的支撑。',
    'projects.key_tech_desc_en': 'Agile chip development relies on modern toolchains and technology stacks, providing strong support for rapid iteration, automated verification, and collaborative development.',
    'projects.tech_highlights_title': '技术亮点',
    'projects.tech_highlights_title_en': 'Technology Highlights',
    'projects.tech_highlight.chisel': '基于Scala的现代硬件构造语言，提供强大的参数化设计能力，支持高层次抽象和代码生成，是敏捷硬件开发的核心使能技术。',
    'projects.tech_highlight.chisel_en': 'A modern hardware construction language based on Scala, offering powerful parameterized design, high-level abstraction, and code generation. It is a core enabling technology for agile hardware development.',
    'projects.tech_highlight.ci': '通过Jenkins、GitLab CI等工具建立自动化工作流，实现代码提交后的自动编译、仿真和验证，确保快速反馈。',
    'projects.tech_highlight.ci_en': 'Establish automated workflows with tools like Jenkins and GitLab CI, enabling automatic compilation, simulation, and verification after code submission for rapid feedback.',
    'projects.tech_highlight.eda': 'OpenROAD、Yosys等开源工具链降低了准入门槛，支持完全开放的设计流程，促进创新和协作。',
    'projects.tech_highlight.eda_en': 'OpenROAD, Yosys and other open-source toolchains lower the entry barrier, support fully open design flows, and foster innovation and collaboration.',
    'projects.tech_highlight.virtual': '利用QEMU、KVM等虚拟化技术进行软硬件协同仿真，在早期阶段验证系统级功能和性能。',
    'projects.tech_highlight.virtual_en': 'Use virtualization technologies such as QEMU and KVM for hardware-software co-simulation, verifying system-level functionality and performance at early stages.',
    'projects.env_title': '现代化开发环境',
    'projects.env_title_en': 'Modern Development Environment',
    'projects.env_desc': '集成先进工具链，实现从设计到验证的全流程自动化',
    'projects.env_desc_en': 'Integrate advanced toolchains to achieve full-process automation from design to verification.',
    'projects.cta_title': '加入开源生态',
    'projects.cta_title_en': 'Join the Open Source Ecosystem',
    'projects.cta_desc': '这些成功项目展示了敏捷芯片开发的巨大潜力。通过参与开源社区，您也可以成为推动硬件开发创新的一份子。',
    'projects.cta_desc_en': 'These successful projects demonstrate the great potential of agile chip development. By participating in the open-source community, you can also be part of driving innovation in hardware development.',
    'projects.cta_explore': '探索开源项目',
    'projects.cta_explore_en': 'Explore Open Source Projects',
    'projects.cta_learn': '了解技术详情',
    'projects.cta_learn_en': 'Learn More About Technologies',

    // Technology Page
    'technology.hero_tag': '核心技术',
    'technology.hero_tag_en': 'Core Technologies',
    'technology.hero_title': '技术',
    'technology.hero_title_en': 'Technology',
    'technology.hero_subtitle': '工具链',
    'technology.hero_subtitle_en': 'Toolchain',
    'technology.intro': '深入了解敏捷芯片开发所依托的现代化技术栈，从高级硬件描述语言到自动化工具链的完整生态系统。',
    'technology.intro_en': 'Gain in-depth understanding of the modern technology stack behind agile chip development, from advanced hardware description languages to a complete ecosystem of automation toolchains.',
    'technology.tabs.tools': '核心工具',
    'technology.tabs.tools_en': 'Core Tools',
    'technology.tabs.workflow': '开发流程',
    'technology.tabs.workflow_en': 'Development Workflow',
    'technology.tabs.practices': '最佳实践',
    'technology.tabs.practices_en': 'Best Practices',
    'technology.tech_stack_title': '技术栈架构',
    'technology.tech_stack_title_en': 'Technology Stack Architecture',
    'technology.tech_stack_layer.0': '开发层',
    'technology.tech_stack_layer.0_en': 'Development Layer',
    'technology.tech_stack_layer.1': '工具层',
    'technology.tech_stack_layer.1_en': 'Tool Layer',
    'technology.tech_stack_layer.2': '实现层',
    'technology.tech_stack_layer.2_en': 'Implementation Layer',
    'technology.future_title': '未来技术趋势',
    'technology.future_title_en': 'Future Technology Trends',
    'technology.future_desc': '随着AI技术的发展，机器学习将深度融入芯片设计流程，包括智能布局布线、自动化验证、设计空间探索等领域。同时，云原生EDA工具和分布式计算将进一步提升开发效率。',
    'technology.future_desc_en': 'With the development of AI technology, machine learning will be deeply integrated into chip design processes, including intelligent placement and routing, automated verification, and design space exploration. Meanwhile, cloud-native EDA tools and distributed computing will further enhance development efficiency.',
    'technology.future.ai': 'AI辅助设计',
    'technology.future.ai_en': 'AI-assisted Design',
    'technology.future.ai_desc': '机器学习优化设计流程',
    'technology.future.ai_desc_en': 'Machine learning optimizes design processes',
    'technology.future.cloud': '云原生EDA',
    'technology.future.cloud_en': 'Cloud-native EDA',
    'technology.future.cloud_desc': '弹性扩展的设计工具',
    'technology.future.cloud_desc_en': 'Elastically scalable design tools',
    'technology.future.open': '开放生态',
    'technology.future.open_en': 'Open Ecosystem',
    'technology.future.open_desc': '标准化的协作平台',
    'technology.future.open_desc_en': 'Standardized collaboration platform',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.philosophy': 'Philosophy',
    'nav.history': 'History',
    'nav.projects': 'Projects',
    'nav.technology': 'Technology',
    
    // Homepage
    'home.title': 'ChipGen',
    'home.ai_expert': 'AI Expert',
    'home.subtitle': 'Agile Chip Development Expert Assistant',
    'home.description': 'Engage with ChipGen AI expert for professional guidance on SoC design, RISC-V architecture, agile methodologies, and cutting-edge chip development practices',
    'home.explore_more': 'Explore More Content',
    'home.core_features': 'Core Features of Agile Chip Development',
    'home.core_features_desc': 'Discover how agile methodologies revolutionize chip development with unprecedented efficiency and innovation',
    'home.achievements': 'Development Achievements',
    'home.achievements_desc': 'Significant milestones achieved by agile chip development worldwide',
    'home.cta_title': 'Start Your Agile Chip Development Journey',
    'home.cta_desc': 'Deep dive into agile methodologies, explore success stories, master core technologies, and join the global open-source chip development community',
    'home.learn_concepts': 'Learn Core Concepts',
    'home.development_history': 'Development History',
    
    // Features
    'feature.fast_iteration': 'Fast Iteration',
    'feature.fast_iteration_desc': 'Achieve agile chip design through short-cycle Sprints',
    'feature.collaborative_teams': 'Collaborative Teams',
    'feature.collaborative_teams_desc': 'Break traditional silos, build flexible collaborative development teams',
    'feature.advanced_tools': 'Advanced Tools',
    'feature.advanced_tools_desc': 'Leverage modern development tools and platforms like Chisel and RISC-V',
    'feature.success_cases': 'Success Cases',
    'feature.success_cases_desc': 'Proven agile methods through projects like Xiangshan and Berkeley RISC-V',
    'common.learn_more': 'Learn More',
    
    // Achievements
    'achievement.manifesto': 'Agile Hardware Manifesto Published',
    'achievement.projects': 'Open Source Chip Projects',
    'achievement.universities': 'Leading Universities Involved',
    'achievement.open_source': 'Open Source Code',
    
    // Chat
    'chat.expert_title': 'ChipGen Expert',
    'chat.expert_subtitle': 'AI Assistant · Online',
    'chat.placeholder': 'Ask questions about agile chip development...',
    'chat.send_hint': 'Press Enter',
    'chat.welcome': 'Hello! I\'m your ChipGen expert assistant. I can answer questions about agile hardware development methodologies, SoC design processes, open-source chip projects, and more. How can I help you today?',
    
    // Thinking process
    'thinking.analyzing': '🤔 Analyzing your question and searching relevant agile chip development knowledge...',
    'thinking.consulting': '🔍 Consulting agile hardware manifesto and SoC design best practices...',
    'thinking.integrating': '⚡ Integrating experiences from RISC-V, Xiangshan processor and other success cases...',
    'thinking.generating': '💡 Generating professional technical insights and recommendations...',
    
    // Chat error messages
    'chat.no_understanding': 'Sorry, I didn\'t understand your question. Please try asking about agile chip development, SoC design, or open-source chip projects.',
    'chat.general_help': 'I apologize, but I cannot answer this question at the moment. However, I can introduce you to the basic concepts, core tools, and success stories of agile chip development. Please try asking more specific questions.',

    // History Page
    'history.hero_tag': '发展历史',
    'history.hero_tag_en': 'History',
    'history.hero_title': '敏捷芯片开发',
    'history.hero_title_en': 'Agile Chip Development',
    'history.hero_subtitle': '发展历程',
    'history.hero_subtitle_en': 'Development History',
    'history.intro': '追溯敏捷方法论在芯片开发领域的演进历程，了解关键里程碑和发展趋势。',
    'history.intro_en': 'Tracing the evolution of agile methodologies in chip development, exploring key milestones and trends.',
    'history.hero_img_title': '从软件到硬件的敏捷之路',
    'history.hero_img_title_en': 'The Agile Journey: From Software to Hardware',
    'history.hero_img_desc': '见证芯片设计方法论的革命性变革',
    'history.hero_img_desc_en': 'Witness the revolutionary transformation of chip design methodologies',
    'history.timeline_title': '关键时间节点',
    'history.timeline_title_en': 'Key Milestones',
    'history.evolution_title': '发展阶段',
    'history.evolution_title_en': 'Evolution Phases',
    'history.evolution_feature': '主要特征：',
    'history.evolution_feature_en': 'Key Features:',
    'history.detail_timeline': '详细时间线',
    'history.detail_timeline_en': 'Detailed Timeline',
    'history.future_title': '未来展望',
    'history.future_title_en': 'Future Outlook',
    'history.future_desc': '随着开源EDA工具的成熟、AI技术的融入以及更多成功案例的涌现，敏捷芯片开发方法论将在未来十年内成为业界主流，推动整个半导体行业向着更加开放、高效、创新的方向发展。',
    'history.future_desc_en': 'With the maturity of open-source EDA tools, the integration of AI technologies, and the emergence of more success stories, agile chip development methodologies are set to become mainstream in the next decade, driving the semiconductor industry towards greater openness, efficiency, and innovation.',
    // Milestones
    'history.milestone.2001.title': '敏捷宣言诞生',
    'history.milestone.2001.title_en': 'Agile Manifesto',
    'history.milestone.2001.desc': '软件工程领域发布敏捷宣言，为后续硬件敏捷开发奠定理论基础',
    'history.milestone.2001.desc_en': 'The Agile Manifesto was published in software engineering, laying the theoretical foundation for agile hardware development.',
    'history.milestone.2001.impact': '理论基础',
    'history.milestone.2001.impact_en': 'Theoretical Foundation',
    'history.milestone.2010.title': 'Chisel语言发布',
    'history.milestone.2010.title_en': 'Chisel Released',
    'history.milestone.2010.desc': 'UC Berkeley发布Chisel硬件构造语言，提供敏捷硬件开发的关键工具',
    'history.milestone.2010.desc_en': 'UC Berkeley released the Chisel hardware construction language, providing a key tool for agile hardware development.',
    'history.milestone.2010.impact': '工具创新',
    'history.milestone.2010.impact_en': 'Tool Innovation',
    'history.milestone.2016.title': '敏捷硬件宣言',
    'history.milestone.2016.title_en': 'Agile Hardware Manifesto',
    'history.milestone.2016.desc': '加州大学伯克利分校正式提出敏捷硬件宣言，标志着敏捷理念系统性应用于硬件',
    'history.milestone.2016.desc_en': 'UC Berkeley formally proposed the Agile Hardware Manifesto, marking the systematic application of agile concepts to hardware.',
    'history.milestone.2016.impact': '方法论确立',
    'history.milestone.2016.impact_en': 'Methodology Established',
    'history.milestone.2019.title': 'RISC-V生态繁荣',
    'history.milestone.2019.title_en': 'RISC-V Ecosystem Flourishes',
    'history.milestone.2019.desc': 'RISC-V指令集架构成熟，为敏捷芯片开发提供开放平台',
    'history.milestone.2019.desc_en': 'The RISC-V ISA matured, providing an open platform for agile chip development.',
    'history.milestone.2019.impact': '生态建设',
    'history.milestone.2019.impact_en': 'Ecosystem Building',
    'history.milestone.2020.title': '全球化应用',
    'history.milestone.2020.title_en': 'Global Adoption',
    'history.milestone.2020.desc': '香山处理器等项目证明敏捷方法在大型芯片项目中的成功应用',
    'history.milestone.2020.desc_en': 'Projects like Xiangshan processor proved the successful application of agile methods in large-scale chip projects.',
    'history.milestone.2020.impact': '产业验证',
    'history.milestone.2020.impact_en': 'Industry Validation',
    // Evolution Phases
    'history.phase.0': '萌芽期',
    'history.phase.0_en': 'Emergence',
    'history.phase.0.period': '2001-2010',
    'history.phase.0.period_en': '2001-2010',
    'history.phase.0.desc': '软件敏捷方法论成熟，开始探索在硬件领域的应用可能性',
    'history.phase.0.desc_en': 'Agile methodologies in software matured, and exploration began for their application in hardware.',
    'history.phase.0.char.0': '理论探索',
    'history.phase.0.char.0_en': 'Theoretical Exploration',
    'history.phase.0.char.1': '工具缺乏',
    'history.phase.0.char.1_en': 'Lack of Tools',
    'history.phase.0.char.2': '概念验证',
    'history.phase.0.char.2_en': 'Proof of Concept',
    'history.phase.1': '发展期',
    'history.phase.1_en': 'Development',
    'history.phase.1.period': '2010-2016',
    'history.phase.1.period_en': '2010-2016',
    'history.phase.1.desc': '关键工具如Chisel出现，学术界开始系统性研究硬件敏捷开发',
    'history.phase.1.desc_en': 'Key tools like Chisel emerged, and academia began systematic research on agile hardware development.',
    'history.phase.1.char.0': '工具涌现',
    'history.phase.1.char.0_en': 'Emergence of Tools',
    'history.phase.1.char.1': '学术研究',
    'history.phase.1.char.1_en': 'Academic Research',
    'history.phase.1.char.2': '小规模实践',
    'history.phase.1.char.2_en': 'Small-scale Practice',
    'history.phase.2': '成熟期',
    'history.phase.2_en': 'Maturity',
    'history.phase.2.period': '2016-至今',
    'history.phase.2.period_en': '2016-Present',
    'history.phase.2.desc': '敏捷硬件宣言发布，大型开源项目验证方法论可行性',
    'history.phase.2.desc_en': 'The Agile Hardware Manifesto was published, and large open-source projects validated the methodology.',
    'history.phase.2.char.0': '方法论确立',
    'history.phase.2.char.0_en': 'Methodology Established',
    'history.phase.2.char.1': '生态完善',
    'history.phase.2.char.1_en': 'Ecosystem Improved',
    'history.phase.2.char.2': '产业应用',
    'history.phase.2.char.2_en': 'Industry Application',

    // Philosophy Page
    'philosophy.hero_tag': '核心理念与方法论',
    'philosophy.hero_tag_en': 'Philosophy & Methodology',
    'philosophy.hero_title': '敏捷芯片开发',
    'philosophy.hero_title_en': 'Agile Chip Development',
    'philosophy.hero_subtitle': '核心理念',
    'philosophy.hero_subtitle_en': 'Core Philosophy',
    'philosophy.intro': '敏捷芯片开发借鉴了软件工程的敏捷思想，旨在应对传统芯片开发模式的挑战。',
    'philosophy.intro_en': 'Agile chip development draws on agile ideas from software engineering to address the challenges of traditional chip development.',
    'philosophy.manifesto_title': '敏捷硬件宣言',
    'philosophy.manifesto_title_en': 'Agile Hardware Manifesto',
    'philosophy.principle.0.title': '可工作的原型优于全面的文档',
    'philosophy.principle.0.title_en': 'Working Prototypes over Comprehensive Documentation',
    'philosophy.principle.0.desc': '注重快速构建可验证的硬件原型，而非完美的设计文档',
    'philosophy.principle.0.desc_en': 'Focus on building verifiable hardware prototypes quickly, rather than perfect design documents.',
    'philosophy.principle.1.title': '协作灵活的团队优于僵化的孤岛',
    'philosophy.principle.1.title_en': 'Collaborative Teams over Rigid Silos',
    'philosophy.principle.1.desc': '打破传统部门壁垒，建立跨学科协作的敏捷团队',
    'philosophy.principle.1.desc_en': 'Break down traditional barriers and build agile, cross-disciplinary teams.',
    'philosophy.principle.2.title': '改进工具和生成器优于改进实例',
    'philosophy.principle.2.title_en': 'Improving Tools & Generators over Improving Instances',
    'philosophy.principle.2.desc': '投资于开发工具和自动化，提高整体开发效率',
    'philosophy.principle.2.desc_en': 'Invest in tool and automation development to improve overall efficiency.',
    'philosophy.principle.3.title': '响应变化优于遵循计划',
    'philosophy.principle.3.title_en': 'Responding to Change over Following a Plan',
    'philosophy.principle.3.desc': '保持灵活性，能够快速适应需求变化和技术发展',
    'philosophy.principle.3.desc_en': 'Stay flexible and adapt quickly to changing requirements and technologies.',
    'philosophy.methodologies_title': '关键方法论',
    'philosophy.methodologies_title_en': 'Key Methodologies',
    'philosophy.method.0.name': 'Scrum for Hardware',
    'philosophy.method.0.name_en': 'Scrum for Hardware',
    'philosophy.method.0.desc': '将Scrum框架应用于硬件开发',
    'philosophy.method.0.desc_en': 'Applying the Scrum framework to hardware development.',
    'philosophy.method.1.name': '测试驱动开发',
    'philosophy.method.1.name_en': 'Test-Driven Development',
    'philosophy.method.1.desc': 'TDD方法在硬件设计中的应用',
    'philosophy.method.1.desc_en': 'Applying TDD in hardware design.',
    'philosophy.method.2.name': '持续集成/验证',
    'philosophy.method.2.name_en': 'Continuous Integration/Verification',
    'philosophy.method.2.desc': 'CI/CV在芯片开发中的实践',
    'philosophy.method.2.desc_en': 'Practicing CI/CV in chip development.',
    'philosophy.method.3.name': '模型驱动开发',
    'philosophy.method.3.name_en': 'Model-Driven Development',
    'philosophy.method.3.desc': 'MDD提高设计抽象层次',
    'philosophy.method.3.desc_en': 'MDD improves the level of design abstraction.',
    'philosophy.benefits_title': '敏捷方法的优势',
    'philosophy.benefits_title_en': 'Benefits of Agile Methods',
    'philosophy.benefit.0.title': '提高效率',
    'philosophy.benefit.0.title_en': 'Increased Efficiency',
    'philosophy.benefit.0.desc': '通过短周期迭代和快速反馈，大幅缩短开发周期',
    'philosophy.benefit.0.desc_en': 'Short-cycle iterations and rapid feedback greatly shorten development cycles.',
    'philosophy.benefit.1.title': '降低风险',
    'philosophy.benefit.1.title_en': 'Reduced Risk',
    'philosophy.benefit.1.desc': '早期验证和持续测试，及时发现和解决问题',
    'philosophy.benefit.1.desc_en': 'Early validation and continuous testing help identify and solve problems promptly.',
    'philosophy.benefit.2.title': '增强创新',
    'philosophy.benefit.2.title_en': 'Enhanced Innovation',
    'philosophy.benefit.2.desc': '灵活响应变化，促进创新思维和技术探索',
    'philosophy.benefit.2.desc_en': 'Flexible response to change fosters innovation and technological exploration.',

    // Projects Page
    'projects.hero_tag': '关键项目与技术',
    'projects.hero_tag_en': 'Key Projects & Technologies',
    'projects.hero_title': '成功',
    'projects.hero_title_en': 'Success',
    'projects.hero_subtitle': '案例展示',
    'projects.hero_subtitle_en': 'Case Studies',
    'projects.intro': '探索全球范围内敏捷芯片开发的成功项目，了解先进技术和工具的实际应用。',
    'projects.intro_en': 'Explore successful agile chip development projects worldwide and learn about the practical application of advanced technologies and tools.',
    'projects.hero_img_title': '开源驱动创新',
    'projects.hero_img_title_en': 'Open Source Drives Innovation',
    'projects.hero_img_desc': 'RISC-V生态推动敏捷芯片开发蓬勃发展',
    'projects.hero_img_desc_en': 'The RISC-V ecosystem drives the flourishing of agile chip development.',
    'projects.case_studies_title': '成功案例',
    'projects.case_studies_title_en': 'Case Studies',
    'projects.visit_project': '访问项目',
    'projects.visit_project_en': 'Visit Project',
    'projects.key_tech_title': '核心技术栈',
    'projects.key_tech_title_en': 'Core Technology Stack',
    'projects.key_tech_desc': '敏捷芯片开发依托于现代化的工具链和技术栈，这些技术为快速迭代、自动化验证和协作开发提供了强有力的支撑。',
    'projects.key_tech_desc_en': 'Agile chip development relies on modern toolchains and technology stacks, providing strong support for rapid iteration, automated verification, and collaborative development.',
    'projects.tech_highlights_title': '技术亮点',
    'projects.tech_highlights_title_en': 'Technology Highlights',
    'projects.tech_highlight.chisel': '基于Scala的现代硬件构造语言，提供强大的参数化设计能力，支持高层次抽象和代码生成，是敏捷硬件开发的核心使能技术。',
    'projects.tech_highlight.chisel_en': 'A modern hardware construction language based on Scala, offering powerful parameterized design, high-level abstraction, and code generation. It is a core enabling technology for agile hardware development.',
    'projects.tech_highlight.ci': '通过Jenkins、GitLab CI等工具建立自动化工作流，实现代码提交后的自动编译、仿真和验证，确保快速反馈。',
    'projects.tech_highlight.ci_en': 'Establish automated workflows with tools like Jenkins and GitLab CI, enabling automatic compilation, simulation, and verification after code submission for rapid feedback.',
    'projects.tech_highlight.eda': 'OpenROAD、Yosys等开源工具链降低了准入门槛，支持完全开放的设计流程，促进创新和协作。',
    'projects.tech_highlight.eda_en': 'OpenROAD, Yosys and other open-source toolchains lower the entry barrier, support fully open design flows, and foster innovation and collaboration.',
    'projects.tech_highlight.virtual': '利用QEMU、KVM等虚拟化技术进行软硬件协同仿真，在早期阶段验证系统级功能和性能。',
    'projects.tech_highlight.virtual_en': 'Use virtualization technologies such as QEMU and KVM for hardware-software co-simulation, verifying system-level functionality and performance at early stages.',
    'projects.env_title': '现代化开发环境',
    'projects.env_title_en': 'Modern Development Environment',
    'projects.env_desc': '集成先进工具链，实现从设计到验证的全流程自动化',
    'projects.env_desc_en': 'Integrate advanced toolchains to achieve full-process automation from design to verification.',
    'projects.cta_title': '加入开源生态',
    'projects.cta_title_en': 'Join the Open Source Ecosystem',
    'projects.cta_desc': '这些成功项目展示了敏捷芯片开发的巨大潜力。通过参与开源社区，您也可以成为推动硬件开发创新的一份子。',
    'projects.cta_desc_en': 'These successful projects demonstrate the great potential of agile chip development. By participating in the open-source community, you can also be part of driving innovation in hardware development.',
    'projects.cta_explore': '探索开源项目',
    'projects.cta_explore_en': 'Explore Open Source Projects',
    'projects.cta_learn': '了解技术详情',
    'projects.cta_learn_en': 'Learn More About Technologies',

    // Technology Page
    'technology.hero_tag': '核心技术',
    'technology.hero_tag_en': 'Core Technologies',
    'technology.hero_title': '技术',
    'technology.hero_title_en': 'Technology',
    'technology.hero_subtitle': '工具链',
    'technology.hero_subtitle_en': 'Toolchain',
    'technology.intro': '深入了解敏捷芯片开发所依托的现代化技术栈，从高级硬件描述语言到自动化工具链的完整生态系统。',
    'technology.intro_en': 'Gain in-depth understanding of the modern technology stack behind agile chip development, from advanced hardware description languages to a complete ecosystem of automation toolchains.',
    'technology.tabs.tools': '核心工具',
    'technology.tabs.tools_en': 'Core Tools',
    'technology.tabs.workflow': '开发流程',
    'technology.tabs.workflow_en': 'Development Workflow',
    'technology.tabs.practices': '最佳实践',
    'technology.tabs.practices_en': 'Best Practices',
    'technology.tech_stack_title': '技术栈架构',
    'technology.tech_stack_title_en': 'Technology Stack Architecture',
    'technology.tech_stack_layer.0': '开发层',
    'technology.tech_stack_layer.0_en': 'Development Layer',
    'technology.tech_stack_layer.1': '工具层',
    'technology.tech_stack_layer.1_en': 'Tool Layer',
    'technology.tech_stack_layer.2': '实现层',
    'technology.tech_stack_layer.2_en': 'Implementation Layer',
    'technology.future_title': '未来技术趋势',
    'technology.future_title_en': 'Future Technology Trends',
    'technology.future_desc': '随着AI技术的发展，机器学习将深度融入芯片设计流程，包括智能布局布线、自动化验证、设计空间探索等领域。同时，云原生EDA工具和分布式计算将进一步提升开发效率。',
    'technology.future_desc_en': 'With the development of AI technology, machine learning will be deeply integrated into chip design processes, including intelligent placement and routing, automated verification, and design space exploration. Meanwhile, cloud-native EDA tools and distributed computing will further enhance development efficiency.',
    'technology.future.ai': 'AI辅助设计',
    'technology.future.ai_en': 'AI-assisted Design',
    'technology.future.ai_desc': '机器学习优化设计流程',
    'technology.future.ai_desc_en': 'Machine learning optimizes design processes',
    'technology.future.cloud': '云原生EDA',
    'technology.future.cloud_en': 'Cloud-native EDA',
    'technology.future.cloud_desc': '弹性扩展的设计工具',
    'technology.future.cloud_desc_en': 'Elastically scalable design tools',
    'technology.future.open': '开放生态',
    'technology.future.open_en': 'Open Ecosystem',
    'technology.future.open_desc': '标准化的协作平台',
    'technology.future.open_desc_en': 'Standardized collaboration platform',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
